name = "proxy"
type = "webpack"
webpack_config = "webpack.config.js"
usage_model = ''
compatibility_flags = []
compatibility_date = "2022-02-25"
zone_id = "b9719f513e0412a652107157cb787e4a"
routes = ["proxy.nest.rip/*"]

# [secrets]
# API_TOKEN

[env.dev]
workers_dev = true

